// <auto-generated />
using Blockexplorer.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Blockexplorer.Entities.Migrations
{
    [DbContext(typeof(ObsidianChainContext))]
    [Migration("20171118165453_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Blockexplorer.Entities.AddressEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(34);

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,8)");

                    b.Property<int>("LastModifiedBlockHeight");

                    b.Property<string>("TxIdBlob");

                    b.HasKey("Id");

                    b.ToTable("AddressEntities");
                });

            modelBuilder.Entity("Blockexplorer.Entities.BlockEntity", b =>
                {
                    b.Property<int>("Id");

                    b.Property<string>("BlockData");

                    b.Property<string>("BlockHash")
                        .HasMaxLength(64);

                    b.Property<int>("Height");

                    b.HasKey("Id");

                    b.HasIndex("BlockHash")
                        .IsUnique()
                        .HasFilter("[BlockHash] IS NOT NULL")
                        .HasAnnotation("SqlServer:Clustered", false);

                    b.ToTable("BlockEntities");
                });

            modelBuilder.Entity("Blockexplorer.Entities.TransactionEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64);

                    b.Property<int?>("BlockEntityId");

                    b.Property<string>("TransactionData");

                    b.HasKey("Id");

                    b.HasIndex("BlockEntityId");

                    b.ToTable("TransactionEntities");
                });

            modelBuilder.Entity("Blockexplorer.Entities.TransactionEntity", b =>
                {
                    b.HasOne("Blockexplorer.Entities.BlockEntity", "BlockEntity")
                        .WithMany("Transactions")
                        .HasForeignKey("BlockEntityId");
                });
#pragma warning restore 612, 618
        }
    }
}
